name: Deploy Project to App Engine

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install

      - name: Run ESLint
        run: npm run lint
      
      - name: Fix ESLint errors
        run: npm run lint:fix
        
      - name: Run Prettier
        run: npm run format

      - name: Build Project
        run: npm run build


      - name: Get the current date and time for version
        run: echo "VERSION_ID=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v2
          credentials: ${{ secrets.GCP_SERVICE_CREDENTIALS }}
          
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"